line-length = 120
show-fixes = true

target-version = 'py312'
exclude = [
    '**/sdk',
    '**/sdks',
    'classic_drivers',
    # To clean up later - exclude from linting till then
    # 'python/voxel/src/voxel/utils/processing',
    # 'python/voxel/tests/processes',
    'microscopes/exaspim-control/src/exaspim_control/voxel_classic',
    'microscopes/exaspim-control/src/exaspim_control/view',
    # 'python/vidgets/src/vidgets/view',
]

[format]
docstring-code-format = true
docstring-code-line-length = 'dynamic'
indent-style = 'space'
quote-style = 'single'

[lint]
select = ['ALL']
ignore = [
    'ANN401',  # Dynamically typed expressions (typing.Any) are disallowed in {name}
    'D',
    'D100',    # Missing docstring in public module
    'D101',    # Missing docstring in public class
    'D102',    # Missing docstring in public method
    'D103',    # Missing docstring in public function
    'D104',    # Missing docstring in public package
    'D105',    # Missing docstring in magic method
    'D107',    # Missing docstring in __init__ method
    'D205',    # One blank line required between summary line and description
    'T201',    # 'Print' found
    'TRY003',  # Specifying long messages outside the exception class (Also EM101, EM102)
    'EM101',   # Exception must not use a string literal, assign to variable first
    'S101',    # Assert detected
    'FBT001',  # Boolean-typed positional argument in function definition
    'FBT002',  # Boolean-typed default value in function definition
    'ERA001',  # Commented out code
    'TD',      # Missing issue link for this TODO, Missing author in TODO; try: `# TODO(<author_name>): ...` or `# TODO @<author_name>:
    'FIX002',  # Line contains TODO, consider resolving the issue
    'RET503',  # Missing explicit `return` at the end of function able to return non-`None` value
    'UP031',   # Use format specifiers instead of percent format
    'INP001',  # implicit-namespace-package
    'PLR0913', # Too many arguments in function definition
    'PLR2004', # Magic value used in comparison, consider using a constant
    'COM812',  # (Redundant when using formatter) missing-trailing-comma
    'S603',    # subprocess-without-shell-equals-true
    'S311',    # Standard pseudo-random generators are not suitable for cryptographic purposes
]

fixable = ['ALL']
unfixable = ['B']
extend-safe-fixes = ['D415', 'D205']

flake8-builtins.ignorelist = ['print']
flake8-quotes = { inline-quotes = 'single', multiline-quotes = 'double' }
pydocstyle = { convention = 'google' }
mccabe = { max-complexity = 14 }
pylint = { max-statements = 75 }

[lint.per-file-ignores]
"!**/src/**.py" = ["D"]                                   # 'Docstring' rules only in src
'**/vidgets/**.py' = ['PLR2004', 'FBT003', 'N802', 'ANN']
'**/examples/**.py' = ['BLE001', 'SLF001', 'ANN']
'**/voxel/utils/**.py' = ['ANN']
'**/exaspim_control/**.py' = ['ANN']

[lint.flake8-annotations]
suppress-none-returning = true
allow-star-arg-any = true
