line-length = 120
show-fixes = true

target-version = "py312"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".gitignore",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "**/sdk",
    "**/sdks",
    # To clean up later - exclude from linting till then
    "python/voxel/src/voxel/utils/processing",
    "python/voxel/tests/processes",
    "python/voxel-classic",
    "python/vidgets/src/vidgets/view",
    "classic_drivers",
]

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
indent-style = "space"

[lint]
extend-select = ["A", "B", "E", "C4", "SIM", "TC"]
unfixable = ["B"]
fixable = ["ALL"]
flake8-builtins.ignorelist = ["print"]
