line-length = 120
show-fixes = true

target-version = "py312"

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".gitignore",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "**/sdk",
    "**/sdks",
    # To clean up later - exclude from linting till then
    "classic_drivers",
    "python/voxel/tests/processes",
    "python/vidgets/src/vidgets/view",
]

lint.extend-select = ["C4", "SIM", "TC"]
lint.fixable = ["ALL"]
