"""Tile — 2D grid-planning unit for the Qt UI.

Ephemeral: generated by grid-planning logic from a GridConfig + FOV, displayed
in the grid table/canvas, and never persisted. Distinct from ``Stack`` (which
is a persisted backend acquisition target) and from ``PreviewTile`` (a camera
preview viewport tile).
"""

from pydantic import BaseModel


class Tile(BaseModel):
    """2D tile position, auto-generated from grid planning.

    All positions and dimensions are in micrometers (µm).
    Positions (x, y) represent the CENTER of the tile.
    Tile bounds extend from (x - w/2, y - h/2) to (x + w/2, y + h/2).
    """

    tile_id: str
    row: int
    col: int
    x: float
    y: float
    w: float  # Full FOV width
    h: float  # Full FOV height
