"""Argument parsing and lazy dispatch for the unified ``vxl`` command."""

import argparse
import sys
from collections.abc import Sequence
from importlib import import_module, util
from ipaddress import IPv4Address
from pathlib import Path
from typing import TextIO
from uuid import UUID

from .check import run_check
from .node import serve as serve_node
from .station import import_catalog
from .station import initialize as initialize_station

_COMMANDS = {"check", "serve", "web", "qt", "node", "station"}
_DEFAULT_HOST = str(IPv4Address(0))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="vxl", description="Voxel microscope control")
    commands = parser.add_subparsers(dest="command", required=True)

    check = commands.add_parser("check", help="statically validate instrument configs")
    check.add_argument("paths", nargs="*", type=Path, help="config files, instrument directories, or collections")
    check.add_argument("--json", action="store_true", dest="as_json", help="emit machine-readable JSON")

    serve = commands.add_parser("serve", aliases=["web"], help="launch the web application")
    serve.add_argument("--host", default=_DEFAULT_HOST, help="bind address (default: all interfaces)")
    serve.add_argument("--port", type=int, default=8000, help="web server port")
    serve.add_argument("--debug", action="store_true", help="enable debug logging")

    qt = commands.add_parser("qt", help="launch the Qt application")
    qt.add_argument("config", nargs="?", type=Path, help="instrument configuration path")
    qt.add_argument("-v", "--verbose", action="store_true", help="enable verbose logging")

    node = commands.add_parser("node", help="run a remote device node")
    node.add_argument("node_id", help="node identifier from the instrument config")
    node.add_argument("--address", "-a", required=True, help="ZMQ bind address")
    node.add_argument("--debug", action="store_true", help="enable debug logging")

    station = commands.add_parser("station", help="manage the local control-station configuration")
    station_commands = station.add_subparsers(dest="station_command", required=True)
    station_init = station_commands.add_parser("init", help="create ~/.voxel/station.yaml")
    station_init.add_argument("--name", required=True, help="human-readable station name")
    station_init.add_argument("--id", type=UUID, dest="station_id", help="stable station UUID (generated by default)")
    station_commands.add_parser(
        "import-catalog",
        help="import the legacy file catalog into records.sqlite3 without modifying its files",
    )
    return parser


def _normalized_argv(argv: Sequence[str]) -> list[str]:
    args = list(argv)
    if not args:
        return ["serve"]
    if args[0] in _COMMANDS or args[0] in {"-h", "--help"}:
        return args
    if args[0].startswith("-"):
        return ["serve", *args]
    return args


def _require(module: str, extra: str, stderr: TextIO) -> bool:
    if util.find_spec(module) is not None:
        return True
    stderr.write(f"This command requires optional {extra} support. Install it with `pip install 'vxl-cli[{extra}]'`.\n")
    return False


def run(
    argv: Sequence[str] | None = None,
    *,
    stdout: TextIO | None = None,
    stderr: TextIO | None = None,
) -> int:
    """Dispatch one CLI invocation and return its process exit code."""
    args = build_parser().parse_args(_normalized_argv(sys.argv[1:] if argv is None else argv))
    output = sys.stdout if stdout is None else stdout
    errors = sys.stderr if stderr is None else stderr

    if args.command == "check":
        return run_check(args.paths, as_json=args.as_json, output=output)

    if args.command in {"serve", "web"}:
        if not _require("vxl_web", "web", errors):
            return 2
        web_app = import_module("vxl_web.station")
        web_app.serve(host=args.host, port=args.port, debug=args.debug)
        return 0

    if args.command == "qt":
        if not _require("vxl_qt", "qt", errors):
            return 2
        qt_app = import_module("vxl_qt.app")
        return qt_app.launch(args.config, verbose=args.verbose)

    if args.command == "node":
        serve_node(args.node_id, args.address, debug=args.debug)
        return 0

    if args.command == "station":
        if args.station_command == "init":
            return initialize_station(args.name, station_id=args.station_id, output=output, errors=errors)
        if args.station_command == "import-catalog":
            return import_catalog(output=output, errors=errors)
        raise AssertionError(f"Unhandled station command: {args.station_command}")

    raise AssertionError(f"Unhandled command: {args.command}")


def main() -> None:
    raise SystemExit(run())
