instrument_name: &instrument_name exaspim

metadata:
  instrument_name: *instrument_name
  experiment_id: example_experiment
  subject_id: 123456
  experimenter_full_name: adam glaser
  immersion_medium: 0.05X SSC
  immersion_medium_index: 1.33
  x_anatomical_orientation: anterior_posterior
  y_anatomical_orientation: inferior_superior
  z_anatomical_orientation: left_right

acquisition:
  z_step_size: 0.5
  tile_overlap: 0.15
  scan_pattern: raster
  scan_direction: row_wise
  start_corner: top_left
  reverse_scan_path: false
  volume_min_corner: (0, 0, 0)
  volume_max_corner: (114.24, 114.24, 50)
  plan_file_path: ./example_plan.yaml
  channels:
    - red
    - green

instrument:
  name: *instrument_name
  description: "A simulated instrument for testing purposes"

  daq:
    conn: Dev1
    tasks:
      acq_clock:
        type: clockgen
        kwds:
          out_pin: PFI0
          counter: ctr0
          freq_hz: 15
          duty_cycle: 0.5
          initial_delay_ms: 0
      acq_task:
        type: wavegen
        kwds:
          sampling_rate_hz: 350000
          period_ms: 10
          trigger_task: acq_clock

  devices:
    simulated_camera_1:
      driver: voxel.drivers.cameras.simulated.SimulatedCamera
      kwds:
        pixel_size_um: 3.5, 3.5
      acq_pin: ao0
    objective_40x:
      driver: voxel.devices.lens.VoxelLens
      kwds:
        magnification: 40
    laser_488:
      driver: voxel.drivers.lasers.simulated.SimulatedLaser
      kwds:
        wavelength: 488
      acq_pin: ao1
    laser_561:
      driver: voxel.drivers.lasers.simulated.SimulatedLaser
      kwds:
        wavelength: 561
      acq_pin: ao2
    z-axis:
      driver: voxel.drivers.linear_axis.simulated.SimulatedLinearAxis
      kwds:
        dimension: Z
      acq_pin: ao3
    etl:
      driver: voxel.drivers.tunable_lenses.simulated.SimulatedTunableLens
      acq_pin: ao4
    x-axis:
      driver: voxel.drivers.linear_axis.simulated.SimulatedLinearAxis
      kwds:
        dimension: X
    y-axis:
      driver: voxel.drivers.linear_axis.simulated.SimulatedLinearAxis
      kwds:
        dimension: Y
    filter_488:
      driver: voxel.drivers.filters.simulated.SimulatedFilter
      kwds:
        wheel: filterwheel
        position: 1
    filter_561:
      driver: voxel.drivers.filters.simulated.SimulatedFilter
      kwds:
        wheel: filterwheel
        position: 2
    filterwheel:
      driver: voxel.drivers.filters.simulated.SimulatedFilterWheel
      kwds:
        wheel_id: 1

  io:
    imaris: &imaris
      driver: voxel.io.writers.imaris.ImarisWriter
    simple_writer: &simple_writer
      driver: voxel.io.writers.simple.SimpleWriter
    robocopy: &robocopy
      driver: voxel.io.transfers.robocopy.RobocopyFileTransfer
      kwds:
        external_path: D:/voxel_test2
        local_path: D:/voxel_test

  channels:
    red:
      camera: simulated_camera_1
      lens: objective_40x
      laser: laser_561
      filter: filter_561
      writer: *imaris
      transfer: *robocopy
    green:
      camera: simulated_camera_1
      lens: objective_40x
      laser: laser_488
      filter: filter_488
      writer: *imaris
      transfer: *robocopy

settings:
  channel.*.camera.acq_waveforms:
    min_voltage: 0.0
    max_voltage: 5.0
    is_digital: True
    rise_point: 0.0
    fall_point: 0.5

  device.simulated_camera_1:
    exposure_time_ms: 20.0
    pixel_type: 16
    roi_height_px: 512
    roi_width_px: 512
    bit_packing_mode: msb
  channel.*.writer:
    compression: lz4shuffle
    pixel_type: uint16
  channel.*.file_transfer:
    verify_transfer: True
    max_retry: 3
    timeout_s: 60
